--- # Deploy

- name: Install dependencies with bundle install
  #TODO make the development part conditonal on rails_env
  command: bash -lc "{{ bundle_path }} install --gemfile {{ current_path }}/Gemfile --path /home/{{ user }}/.gem --deployment" #--without development test"
  environment: 
    LANG: en_US.UTF-8
    # Note: the 'LANG={{ language }}' is a fix for jquery-rails 1.0.17... fails even though server has correct locale setting
    #LANG: "{{ language }}"
  tags: bundle_app

- name: Setup database with rake migrate
  command: bash -lc "{{ bundle_path }} exec rake db:migrate" chdir="{{ current_path }}"
  tags: rake

- name: Seed database
  # We run a shell script that passes the default email and password to rake with an EOF block, so we don't hang on the prompts.
  command: bash -lc "{{ shared_path }}/config/seed.sh" chdir="{{ current_path }}"
  tags: seed

- name: Precompile primary
  command: bash -lc "{{ bundle_path }} exec rake assets:precompile:primary RAILS_GROUPS=assets" chdir="{{ current_path }}"
  tags: precompile

- name: Precompile nondigest
  command: bash -lc "{{ bundle_path }} exec rake assets:precompile:nondigest RAILS_GROUPS=assets" chdir="{{ current_path }}"
  tags: precompile
