--- # Deploy

- name: Clone repo 
  git: repo="{{ repo }}" dest="{{ current_path }}"

- name: Install dependencies with bundle install
  shell: LANG=en_US.UTF-8 {{ bundle_path }} install --gemfile {{ current_path }}/Gemfile --path /home/{{ user }}/.gem --deployment --without development test
  tags: bundle_app

  # TODO use variables for spree email etc propts for full automation.
- name: Setup database with rake schema load
  command: "{{ bundle_path }} exec rake db:migrate chdir={{ current_path }}" 
  environment: "{{ env }}"
  tags: rake
  
- name: Seed database
  command: "{{ bundle_path }} exec rake db:seed chdir={{ current_path }}"
  environment: "{{ env }}"
  tags: rake

- name: precompile primary
  command: "{{ bundle_path }} exec rake assets:precompile:primary RAILS_GROUPS=assets chdir={{ current_path }}" 
  environment: "{{ env }}"
  tags: precompile

- name: precompile primary
  command: "{{ bundle_path }} exec rake assets:precompile:nondigest RAILS_GROUPS=assets chdir={{ current_path }}" 
  environment: "{{ env }}"
  tags: precompile
