---
- name: deploy
  hosts: ofn_servers
  remote_user: "{{ user }}"
  vars_files:
    - vars.yml
  roles:
    - role: deploy
      notify:
        - restart unicorn
  handlers:
    - include: roles/webserver/handlers/main.yml
