---
- hosts: all

  vars:
    ruby: ruby-1.9.3-p392
    phantomjs: phantomjs-1.9.0-linux-x86_64
    dev_db: dev
    test_db: test
    db_user_name: ofn
    db_pass: f00d

    # OFN variables
    app: openfoodnetwork
    app_user: openfoodweb1
    application: openfoodnetwork
    app_path: "/home/{{ app_user }}/apps/{{ application }}"
    shared_path: "{{ app_path }}/shared"

    # Unicorn variables (from cap unicorn.rb)
    unicorn_user: {{ app_user }}
    unicorn_pid: {{ app_path }}/tmp/pids/unicorn.pid
    unicorn_config: {{ shared_path }}/config/unicorn.rb
    unicorn_log: {{ shared_path }}/log/unicorn.log
    git_post_receive: {{app_path }}/.git/hooks/post-receive
    unicorn_workers: 2
    unicorn_timeout: 30

    # nginx variables
    protocol: http
    domain: www.openfoodnetwork.org
    app_root: /vagrant
    port: 3000

  roles:
    - common
    - zzet.rbenv
    - webserver
    - mortik.nginx-rails
    - dbserver
    - ofn

