---
- hosts: all

  vars:
    ruby: ruby-1.9.3-p392
    phantomjs: phantomjs-1.9.0-linux-x86_64
    dev_db: dev
    test_db: test
    db_user_name: ofn
    db_pass: f00d

    # OFN variables
    app: openfoodnetwork
    app_user: openfoodweb1
    application: openfoodnetwork
    shared_path: "/home/{{ app_user }}/apps/{{ application }}/shared"

    # nginx variables
    protocol: http
    domain: www.openfoodnetwork.org
    app_root: /vagrant
    port: 3000

  roles:
    - common
    - zzet.rbenv
    - webserver
    - mortik.nginx-rails
    - dbserver
    - ofn

