---
- hosts: all
  remote_user: ubuntu

  vars:
    user: ubuntu
    ruby: ruby-1.9.3-p392
    phantomjs: phantomjs-1.9.0-linux-x86_64

    # Database
    db: ofn
    test_db: ofn_test
    db_user_name: ofn_user
    db_pass: f00d

    # nginx variables
    protocol: http
    domain: www.openfoodnetwork.org
    app_root: "{{ current_path }}"
    port: 3000

    # OFN variables
    app: openfoodnetwork
    application: "{{ app }}"
    app_path: "/home/{{ user }}/apps/{{ app }}"
    current_path: "{{ app }}/current"
    build_path: "{{ app }}/build"
    shared_path: "{{ app_path }}/shared"

    # rails deploy variables
    rails_env: production
    home_directory: "/home/{{ user }}"

    # Unicorn variables
    unicorn_user: "{{ user }}"
    unicorn_config: "{{ shared_path }}/config/unicorn.rb"
    unicorn_log: "{{ shared_path }}/log/unicorn.log"
    unicorn_pid: "{{ current_path }}/tmp/pids/unicorn.pid"
    git_post_receive: "{{ current_path }}/.git/hooks/post-receive"
    unicorn_workers: 2
    unicorn_timeout: 30

  roles:
    - common
    - zzet.rbenv
    - webserver
    - mortik.nginx-rails
       # Use custom unicorn config template.
       templates:
         - { 
           src: "roles/webserver/templates/nginx_unicorn" 
           dest: "{{ nginx_path }}/sites-available/{{ app }}" 
           owner: root
           group: root
           mode: "0600"
         }
    - dbserver
    - ofn

    - role: nicolai86.prepare-release
      repo: git@github.com:openfoodfoundation/openfoodnetwork.git
      branch: master

      symlinks:
        - { src: "{{ shared_path }}/public/assets", dest: "{{ current_path }}/public/assets" }
        - { src: "{{ shared_path }}/public/system", dest: "{{ current_path }}/public/system" }
        - { src: "{{ shared_path }}/config/database.yml", dest: "{{ current_path }}/config/database.yml" }

      directories:
        - "{{ shared_path }}/config"

      templates:
        - { src: "templates/env.js", dest: "{{ shared_path }}/.env" }

      tags: deploy

    - role: nicolai86.rails-deployment
      migrate: yes
      compile_assets: yes
      force_migrate: no
      force_asset_compilation: no
      tags: deploy

    - role: nicolai86.finalize-release
      tags: deploy

    - role: restart
      service: application:*
      tags:
        - deploy
        - rollback
