---
- hosts: do
  remote_user: ubuntu

  vars:
    user: ubuntu
    ruby: ruby-1.9.3-p392
    phantomjs: phantomjs-1.9.0-linux-x86_64
    bundle: /home/ubuntu/.rbenv/shims/bundle

    # Database
    db: openfoodnetwork
    test_db: ofn_test
    db_user: ofn_user
    db_pass: f00d
    db_host: localhost

    # OFN variables
    app: openfoodnetwork
    application: "{{ app }}"
    home_path: "/home/{{ user }}"
    app_path: "{{ home_path }}/apps/{{ app }}"
    current_path: "{{ app_path }}/current"
    build_path: "{{ app_path }}/build"
    shared_path: "{{ app_path }}/shared"
    repo: https://github.com/openfoodfoundation/openfoodnetwork.git

    # Rails deploy variables
    rails_env: production
    home_directory: "{{ home_path }}"

    # Nginx variables
    protocol: http
    domain: www.openfoodnetwork.org
    app_root: "{{ current_path }}"
    port: 3000

    # Unicorn variables
    unicorn_user: "{{ user }}"
    unicorn_config: "{{ shared_path }}/config/unicorn.rb"
    unicorn_log: "{{ shared_path }}/log/unicorn.log"
    unicorn_pid: "{{ current_path }}/tmp/pids/unicorn.pid"
    git_post_receive: "{{ current_path }}/.git/hooks/post-receive"
    unicorn_workers: 2
    unicorn_timeout: 30

  roles:

    - common # runs fine

    - role: zzet.rbenv # runs fine
      rbenv:
        env: user
        version: v0.4.0
        ruby_version: 1.9.3-p392
      rbenv_users: 
      - { name: "ubuntu", home: "/home/ubuntu/", comment: "Main user" }
      sudo: yes

    - bundler

    - role: dbserver # sometimes hangs - was it language?
      tags: db

    - role: ofn
      tags: ofn

    - role: webserver # runs fine - unicorn wont start without project?
      tags: ws

    - role: "mortik.nginx-rails" # runs fine, wont start?
      sudo: yes
      tags: nginx

