---

- hosts: ofn_servers
  remote_user: "{{ user }}"
  sudo: yes
  sudo_user: "{{ unicorn_user }}"

  vars_files:
    - vars/default_vars.yml
    - vars.yml

  handlers:
    - include: roles/webserver/handlers/main.yml
    - include: roles/deploy/handlers/main.yml

  roles:
    - role: rollback
