---
# Add the default user as root. AWS ubuntu images generally have a 
# default user (ubuntu) and wont let this be run as root. But digital ocean images don't.

- hosts: all
  remote_user: root
  vars_files:
    - vars.yml
  roles: 
    - default_user


