---
s3_headers: "{\"Cache-Control\":\"max-age=31557600\"}"
s3_protocol: "https"

attachment_url: "/spree/products/:id/:style/:basename.:extension"
attachment_styles: "{\"mini\":[\"48x48\u003E\",\"\"],\"small\":[\"100x100\u003E\",\"\"],\"product\":[\"240x240\u003E\",\"\"],\"large\":[\"600x600\u003E\",\"\"]}"
attachment_path: "public/spree/products/:id/:style/:basename.:extension"
attachment_default_style: "product"
attachment_default_url: "/spree/products/:id/:style/:basename.:extension"

stripe_client_id:
stripe_instance_secret_key:
stripe_instance_publishable_key:
stripe_endpoint_secret:
