---
- name: Install language package(s)
  apt: pkg={{ item }} state=latest
  with_items: "{{ language_packages }}"

- name: Update locales
  shell: "update-locale LANG={{ language }} LC_ALL={{ language }} LC_CTYPE={{ language }}"
  sudo: yes
    
- name: Reconfigure locales
  shell: "dpkg-reconfigure locales"
  sudo: yes
