---
- name: install language package(s)
  become: yes
  apt: pkg={{ item }} state=latest force=yes
  with_items: language_packages

- name: update locales
  shell: "update-locale LANG={{ language }} LC_ALL={{ language }} LC_CTYPE={{ language }}"
  become: yes

- name: reconfigure locales
  shell: "dpkg-reconfigure locales"
  become: yes
