--- # App

# Setup shared files and folders

- name: Make dirs
  file: path={{ item }} state=directory
  with_items:
    - "{{ app_path }}"
    - "{{ shared_path }}"
    - "{{ backup_path }}"
    - "{{ assets_path }}"
    - "{{ system_path }}"
    - "{{ spree_path }}"
    - "{{ log_path }}"
    - "{{ pid_path }}"
    - "{{ sock_path }}"
    - "{{ config_path }}"

  tags: dirs

- name: Template files
  template: src={{ item.src }} dest={{ item.dest }} mode=775
  with_items:
    - { src: "post-receive", dest: "{{ config_path }}/post-receive" }
    - { src: "seed.sh", dest: "{{ config_path }}/seed.sh" }
      
- name: Copy the newrelic.yml to shared folder
  template: src=newrelic.yml dest={{ shared_path }}/config/newrelic.yml mode=775
  when: newrelic_key != "none"

- name: Copy the s3.yml to shared folder
  template: src=s3.yml dest={{ shared_path }}/config/s3.yml mode=775
  when: s3_bucket != "none"


# This is a temporary solution to having hard coded australian data in the repo,
# without adding a fork that does the same thing for the elsewhere. So we just copy over the files.

- name: Copy files
  copy: src={{ item.src }} dest={{ item.dest }} mode=775 force=yes
  with_items:
    - { src: "files/seeds.rb", dest: "{{ config_path }}/seeds.rb" }
    - { src: "files/suburb_seeds.rb", dest: "{{ config_path }}/suburb_seeds.rb" }
    - { src: "files/spree.rb", dest: "{{ config_path }}/spree.rb" }
    - { src: "files/states.yml", dest: "{{ config_path }}/states.yml" }
    - { src: "files/countries.yml", dest: "{{ config_path }}/countries.yml" }

# Cron. TODO use ansible cron module for this.
- name: Generate the crontab file for automated backups.
  template: src=crontab.j2 dest={{ home_path }}/crontab

- name: Setup cron for the user
  sudo: yes
  command: "crontab -u {{ user }} {{ home_path }}/crontab"
