--- # common

- name: Update apt
  apt: update_cache=yes
  sudo: yes

  #TODO remove unnecesary packages from this list.
- name: Install base packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - build-essential
    - git-core
    - nodejs
    - imagemagick
    - fail2ban
    - curl
    - python-pycurl
    - python-psycopg2 # needed for some ansible libraries
    - python-software-properties
    - libpq-dev
    - unattended-upgrades
    - tklib
    - zlib1g-dev 
    - libssl-dev
    - libreadline-gplv2-dev
    - libxml2 
    - libxml2-dev 
    - libxslt1-dev
    - ranger
    #- fontconfig # needed for phantomjs
    #- nfs-common # make virtualbox faster
    
- name: Copy up .bashrc
  template: dest=/{{ home_path }}/.bashrc src=bashrc

- name: Copy up .bash_profile
  template: dest=/{{ home_path }}/.bash_profile src=bash_profile
