--- # common

- name: update apt
  apt: update_cache=yes
  sudo: yes

  #TODO remove unnecesary packages from this list.
- name: install base packages
  apt: pkg={{ item }} state=latest force=yes
  sudo: yes
  with_items:
    - build-essential
    - git-core
    - nodejs
    - imagemagick
    - fail2ban
    - curl
    - python-pycurl
    - python-psycopg2 # needed for some ansible libraries
    - python-software-properties
    - libpq-dev
    - unattended-upgrades
    - tklib
    - zlib1g-dev
    - libssl-dev
    #- libreadline-gplv2-dev
    - libxml2
    - libxml2-dev
    - libxslt1-dev
    - memcached
    - ranger
    - monit
    #- fontconfig # needed for phantomjs
    #- nfs-common # make virtualbox faster

- name: copy up .bashrc (admin user)
  template: src=bashrc.j2 dest={{ home_path }}/.bashrc

- name: copy up .bash_profile (admin user)
  template: src=bash_profile.j2 dest={{ home_path }}/.bash_profile

- name: copy up .bashrc (unicorn user)
  template: src=bashrc.j2 dest={{ unicorn_home_path }}/.bashrc
  sudo: yes
  sudo_user: "{{ unicorn_user }}"

- name: copy up .bash_profile (unicorn user)
  template: src=bash_profile.j2 dest={{ unicorn_home_path }}/.bash_profile
  sudo: yes
  sudo_user: "{{ unicorn_user }}"

- name: configure monit
  template: src=monit.j2 dest=/etc/monit/conf.d/{{ app }}
  sudo: yes
