--- # dbserver

- name: Install postgres packages
  apt: pkg={{ item }} state=latest force=yes
  sudo: yes
  with_items:
    - postgresql
    - postgresql-client
    - postgresql-contrib
    
- name: Create db user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ db_user }} password={{ db_pass }} role_attr_flags=SUPERUSER

- name: Generate the .pgpass file
  template: src=pgpass.j2 dest={{ home_path }}/.pgpass mode=600

