--- # dbserver

- name: Install postgres packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - postgresql
    - postgresql-client
    - postgresql-contrib
    
- name: create db user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ db_user }} password={{ db_pass }} role_attr_flags=SUPERUSER

- name: Generate the database configuration file.
  template: src=postgresql.yml dest={{ config_path }}/database.yml mode=0775

- name: Generate the .pgpass file
  template: src=pgpass dest={{ home_path }}/.pgpass mode=600

