---
- name: make config dir
  file: path={{ shared_path }}/config state=directory

- name: copy unicorn_init
  template: src=unicorn_init dest=/etc/init.d/unicorn_{{ app }}
  sudo: yes

- name: copy unicorn.rb
  template: src=unicorn.rb dest={{ shared_path }}/config/unicorn.rb
    
- name: update unicorn 
  shell: update-rc.d -f unicorn_{{ app }} defaults
  sudo: yes

- name: run unicorn
  service: name=unicorn_{{ app }} state=started
  sudo: yes
  # TODO: #     after "deploy:#{command}", "unicorn:#{command}"

#- name: install rvm
  #shell: \curl -L https://get.rvm.io | bash -s stable --autolibs=3 creates=~/.rvm

#- name: install ruby
  #shell: /usr/local/rvm/bin/rvm install --default {{ ruby }} creates=~/.rvm/rubies/{{ ruby }}
  # sudo: yes

- name: download phantomjs
  get_url: url=https://phantomjs.googlecode.com/files/{{ phantomjs }}.tar.bz2
           dest=/var/tmp/{{ phantomjs }}.tar.bz2
  sudo: yes

- name: untar phantomjs
  shell: chdir=/var/tmp tar xjf {{ phantomjs }}.tar.bz2 creates=/var/tmp/{{ phantomjs }}
  sudo: yes

- name: symlink the phantomjs executable
  file: dest=/usr/bin/phantomjs src=/var/tmp/{{ phantomjs }}/bin/phantomjs state=link
  sudo: yes

