--- # webserver
- name: make config dir
  file: path={{ shared_path }}/config state=directory

- name: make config dir
  file: path={{ shared_path }}/log state=directory

- name: make config dir
  file: path={{ current_path }}/tmp/pids state=directory

- name: copy unicorn_init
  template: src=unicorn_init dest=/etc/init.d/unicorn_{{ app }} mode=744
  sudo: yes
  tags: unicorn

- name: copy unicorn.rb
  template: src=unicorn.rb dest={{ shared_path }}/config/unicorn.rb
  tags: unicorn
    
- name: update unicorn 
  shell: update-rc.d -f unicorn_{{ app }} defaults
  sudo: yes
  tags: unicorn

- name: setup uniconr with nginx
  template: src=roles/webserver/templates/nginx_unicorn dest={{ nginx_path }}/sites-available/{{ app }} owner=root group=root mode=0600
  sudo: yes
  tags: unicorn-nginx

- name: run unicorn
  service: name=unicorn_{{ app }} state=started
  sudo: yes
  tags: unicorn
  # TODO: #     after "deploy:#{command}", "unicorn:#{command}"

#- name: download phantomjs
  #get_url: url=https://phantomjs.googlecode.com/files/{{ phantomjs }}.tar.bz2
           #dest=/var/tmp/{{ phantomjs }}.tar.bz2
  #sudo: yes

#- name: untar phantomjs
  #shell: chdir=/var/tmp tar xjf {{ phantomjs }}.tar.bz2 creates=/var/tmp/{{ phantomjs }}
  #sudo: yes

#- name: symlink the phantomjs executable
  #file: dest=/usr/bin/phantomjs src=/var/tmp/{{ phantomjs }}/bin/phantomjs state=link
  #sudo: yes

