---
- name: create a new server
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    digitalocean_api_token: "{{ lookup('env','DO_API_TOKEN') }}"
    # Run this to get a list of keys and their IDs:
    # curl -X GET --silent "https://api.digitalocean.com/v2/account/keys?per_page=999" -H "Authorization: Bearer $DO_API_TOKEN" |jq '.'
    digitalocean_ssh_key_ids:
      - 293224

    # Default Digital Ocean settings for UK. Edit these for other configurations.
    droplet_region_id: lon1
    # Ubuntu 14.04.5 x64
    droplet_image_id: 22256351
    droplet_size_id: 2gb
    # Name must have pattern: a-z, A-Z, 0-9, . and -
    droplet_name: ofn-uk-test
    droplet_groups: uk-dynamic

  roles:
    - conorsch.create-droplet
