---
- name: setup
  hosts: ofn_servers
  remote_user: "{{ user }}"

  tasks:
  # - name: create host_vars file
  #   debug: msg={{user_pass}}

  - command: "psql -U ubuntu -d openfoodnetwork -c'SELECT name FROM enterprises'"

  # - name: dump all vars
  #   local_action: template src=templates/dumpall.j2 dest=./ansible.all.txt
