---
- name: deploy
  hosts: ofn_servers
  remote_user: "{{ user }}"
  become: yes
  become_user: "{{ unicorn_user }}"

  vars_files:
    - ../vars/default_vars.yml
    # - vars.yml

  roles:
    - role: deploy
      notify:
        - restart unicorn

  handlers:
    - include: roles/webserver/handlers/main.yml
