---

- hosts: ofn_servers
  remote_user: "{{ user }}"
  become: yes
  become_user: "{{ unicorn_user }}"

  handlers:
    - include: ../roles/webserver/handlers/main.yml
    - include: ../roles/deploy/handlers/main.yml

  roles:
    - role: rollback
