---
- name: ruby_update
  hosts: ofn_servers
  remote_user: "{{ user }}"

  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
      become: yes

  roles:
    - role: zzet.rbenv # Install ruby. If missing run: ansible-galaxy install zzet.rbenv
      become: yes
      rbenv:
        env: user
        version: v1.0.0
        default_ruby: "{{ ruby_version }}"
        rubies:
          - version: "{{ ruby_version }}"
      rbenv_users:
        - { name: "{{ unicorn_user }}", home: "{{ unicorn_home_path }}", comment: "Main user"}
      tags: ruby
