---
# Check that the server is online and functional

# WARNING: The verify role is semi-destructive. It saves and loads the staging baseline,
# which will stop and start the server, resulting in downtime. The database contents
# will probably remain the same, but that is not guaranteed.
# NOT INTENDED TO BE RUN ON A PRODUCTION SERVER.

- hosts: ofn_servers
  remote_user: "{{ user }}"
  become: yes
  become_user: "{{ unicorn_user }}"

  roles:
    - verify