---

- name: add postgresql signing key
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
  become: yes

- name: add offical postgresql repo
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    filename: pgdg
  become: yes

- name: install postgres {{ pg_new }}
  apt:
    name: "postgresql-{{ pg_new }}"
  become: yes

- name: drop new custer
  command: pg_dropcluster --stop {{ pg_new }} main
  become: yes

- name: create new custer with matching locale
  command: >
    pg_createcluster --start --locale {{ postgres_cluster_collation.query_result[0].datctype }} {{ pg_new }} main
  become: yes
