---

# User name and password for running ansible on host
user: ofn-admin

# Connecting to the server
#   ssh_pubkey - Location of the SSH public key file for the user created by
#   running "ansible user.yml -f 10"  The location given is the path on your
#   local machine.  Ex: "{{ lookup('file', '~/.ssh/ofn_rsa.pub') }}"
# The Ansible scripts will put it up onto the proper location on the OFN server.
# This might be used by hosts (like DigitalOcean) that require or encourage you
# to connect using SSH instead of just passwords.
ssh_pubkey: "{{ lookup('file', '~/.ssh/{{ ssh_pubkey_name }}') }}"

protocol: https

git_repo: https://github.com/openfoodfoundation/openfoodnetwork.git
git_version:  v1.7.0

l10n_git_version: HEAD



###########################################################################################
# OTHER VARIABLES - You can probably go with the herd and leave these as is.

#----------------------------------------------------------------------
# Rails variables
ruby: 2.1.5
gem_path: /home/{{ user }}/.gem
bundle_path: /home/{{ user }}/.rbenv/shims/bundle
env:
  RAILS_ENV: "{{ rails_env }}"
  PATH: "{{ gem_home }}/bin:{{ ansible_env.PATH }}"
#phantomjs: phantomjs-1.9.0-linux-x86_64

#----------------------------------------------------------------------
# Database variables
db: openfoodnetwork
test_db: ofn_test
db_user: ofn_user
db_host: localhost

#----------------------------------------------------------------------
# App variables
app: openfoodnetwork
# Paths
home_path: "/home/{{ user }}"
unicorn_home_path: "/home/{{ unicorn_user }}"
app_path: "{{ unicorn_home_path }}/apps/{{ app }}"
current_path: "{{ app_path }}/current"
repo_path: "{{ app_path }}/repo"
build_path: "{{ app_path }}/build"
shared_path: "{{ app_path }}/shared"
backup_path: "{{ app_path }}/backups"
releases_path: "{{ app_path }}/releases-old"
rollback_path: "{{ app_path }}/rollback"
rollback_sql_path: "{{ app_path }}/rollback.sql.gz"
assets_path: "{{ shared_path }}/assets"
system_path: "{{ shared_path }}/system"
spree_path: "{{ shared_path }}/spree"
config_path: "{{ shared_path }}/config"
log_path: "{{ shared_path }}/log"
pid_path: "{{ shared_path }}/pids"
sock_path: "{{ shared_path }}/sock"
l10n_path: "{{ shared_path }}/l10n"
git_post_receive: "{{ current_path }}/.git/hooks/post-receive"

#----------------------------------------------------------------------
# Nginx variables
app_root: "{{ current_path }}"
port: 3000
# domain: is set above

#----------------------------------------------------------------------
# Unicorn variables
# User name for the unprivileged user which runs unicorn
unicorn_user: openfoodnetwork
unicorn_config: "{{ config_path }}/unicorn.rb"
unicorn_log: "{{ log_path }}/unicorn.log"
unicorn_pid: "{{ pid_path }}/unicorn.pid"
unicorn_sock: "{{ sock_path }}/unicorn.{{ app }}.sock"
unicorn_workers: 2
unicorn_timeout: 30

