---

# User name and password for running scripts
user: ubuntu

# User name for the unprivileged user which runs unicorn
unicorn_user: openfoodnetwork

# Connecting to the server
#   ssh_pubkey - Location of the SSH public key file for the user created by
#   running "ansible user.yml -f 10"  The location given is the path on your
#   local machine.  Ex: "{{ lookup('file', '~/.ssh/ofn_rsa.pub') }}"
# The Ansible scripts will put it up onto the proper location on the OFN server.
# This might be used by hosts (like DigitalOcean) that require or encourage you
# to connect using SSH instead of just passwords.
ssh_pubkey: "{{ lookup('file', '~/.ssh/ofn_rsa.pub') }}"

protocol: https


##----------------------
##  BACKUPS

# Paths
#   local_backup_path - Place to store database backups on your local machine (where ansible runs)  when running the backup task. Ex: /home/your_username/backups/{{ app }}
#   local_rsync_path - Place to store rsynced files locally when running the backup task. Ex: /home/your_username/backups/{{ app }}
local_backup_path: /Users/pmackay/dev/openfoodnetwork/backups/{{ app }}
local_rsync_path: /Users/pmackay/dev/openfoodnetwork/backups/{{ app }}



###########################################################################################
# OTHER VARIABLES - You can probably go with the herd and leave these as is.

#----------------------------------------------------------------------
# Rails variables
ruby: 1.9.3-p392
gem_path: /home/{{ user }}/.gem
bundle_path: /home/{{ user }}/.rbenv/shims/bundle
env:
  RAILS_ENV: "{{ rails_env }}"
  PATH: "{{ gem_home }}/bin:{{ ansible_env.PATH }}"
#phantomjs: phantomjs-1.9.0-linux-x86_64

#----------------------------------------------------------------------
# Database variables
db: openfoodnetwork
test_db: ofn_test
db_user: ofn_user
db_host: localhost

#----------------------------------------------------------------------
# App variables
app: openfoodnetwork
# Paths
home_path: "/home/{{ user }}"
app_path: "{{ home_path }}/apps/{{ app }}"
current_path: "{{ app_path }}/current"
repo_path: "{{ app_path }}/repo"
build_path: "{{ app_path }}/build"
shared_path: "{{ app_path }}/shared"
backup_path: "{{ app_path }}/backups"
releases_path: "{{ app_path }}/releases-old"
rollback_path: "{{ app_path }}/rollback"
rollback_sql_path: "{{ app_path }}/rollback.sql.gz"
assets_path: "{{ shared_path }}/assets"
system_path: "{{ shared_path }}/system"
spree_path: "{{ shared_path }}/spree"
config_path: "{{ shared_path }}/config"
log_path: "{{ shared_path }}/log"
pid_path: "{{ shared_path }}/pids"
sock_path: "{{ shared_path }}/sock"
git_post_receive: "{{ current_path }}/.git/hooks/post-receive"

#----------------------------------------------------------------------
# Nginx variables
app_root: "{{ current_path }}"
port: 3000
# domain: is set above

#----------------------------------------------------------------------
# Unicorn variables
# unicorn_user: "{{ user }}"
unicorn_config: "{{ config_path }}/unicorn.rb"
unicorn_log: "{{ log_path }}/unicorn.log"
unicorn_pid: "{{ pid_path }}/unicorn.pid"
unicorn_sock: "{{ sock_path }}/unicorn.{{ app }}.sock"
unicorn_workers: 2
unicorn_timeout: 30

