---

# See https://github.com/openfoodfoundation/ofn-install/wiki/Setup for more info
checkout_zone: Europe
country_code: FR
currency: EUR
locale: fr
language: fr.UTF-8
language_packages:
  - language-pack-fr-base
l10n_repo: https://github.com/openfoodfoundation/l10n_fr.git
timezone: Paris


developer_email: info@openfoodfrance.fr

