---

# See https://github.com/openfoodfoundation/ofn_deployment/wiki/Setup for more info
checkout_zone: Europe
country_code: GB
currency: GBP
locale: en-GB
language: en_GB.UTF-8
language_packages:
  - language-pack-en-base
l10n_repo: https://github.com/openfoodfoundation/l10n_gb.git
timezone: London


