name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  ansible-lint:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: ansible/ansible-lint-action@master
        with:
          targets: "playbooks/*.yml"
          override-deps: |
            ansible==2.9
            ansible-lint==4.2.0
          args: "--exclude community"

  playbook-tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ansible
        run: |
          pip install -r requirements.txt
          bin/setup

      - name: Test Playbooks
        run: ansible-playbook tests/suite.yml --limit travis --connection local
